// GENERATED by `bun run themes:generate` — do not edit by hand.
// Omachi first (the default; it needs no CSS overrides), then the Omarchy
// built-in themes from /usr/share/omarchy/themes, alphabetical by id.

export interface ColorThemeMeta {
	/** data-color-theme attribute value and the localStorage["color-theme"] key. */
	id: string;
	label: string;
	/** The palette's authentic mode from colors.toml. */
	mode: "light" | "dark";
	/** Native accent and background hexes, for picker swatches. */
	accent: string;
	background: string;
}

export const COLOR_THEMES: ColorThemeMeta[] = [
	{ id: "omachi", label: "Omachi", mode: "dark", accent: "#005fc6", background: "#ffffff" },
	{ id: "catppuccin", label: "Catppuccin", mode: "dark", accent: "#89b4fa", background: "#1e1e2e" },
	{ id: "catppuccin-latte", label: "Catppuccin Latte", mode: "light", accent: "#1e66f5", background: "#eff1f5" },
	{ id: "ethereal", label: "Ethereal", mode: "dark", accent: "#7d82d9", background: "#060B1E" },
	{ id: "everforest", label: "Everforest", mode: "dark", accent: "#7fbbb3", background: "#2d353b" },
	{ id: "flexoki-light", label: "Flexoki Light", mode: "light", accent: "#205EA6", background: "#FFFCF0" },
	{ id: "gruvbox", label: "Gruvbox", mode: "dark", accent: "#7daea3", background: "#282828" },
	{ id: "hackerman", label: "Hackerman", mode: "dark", accent: "#82FB9C", background: "#0B0C16" },
	{ id: "kanagawa", label: "Kanagawa", mode: "dark", accent: "#dcd7ba", background: "#1f1f28" },
	{ id: "last-horizon", label: "Last Horizon", mode: "dark", accent: "#b59790", background: "#0c0b0c" },
	{ id: "lumon", label: "Lumon", mode: "dark", accent: "#8bc9eb", background: "#16242d" },
	{ id: "lupine", label: "Lupine", mode: "light", accent: "#3264eb", background: "#fafafa" },
	{ id: "matte-black", label: "Matte Black", mode: "dark", accent: "#e68e0d", background: "#121212" },
	{ id: "miasma", label: "Miasma", mode: "dark", accent: "#78824b", background: "#222222" },
	{ id: "nord", label: "Nord", mode: "dark", accent: "#81a1c1", background: "#2e3440" },
	{ id: "osaka-jade", label: "Osaka Jade", mode: "dark", accent: "#509475", background: "#111c18" },
	{ id: "retro-82", label: "Retro 82", mode: "dark", accent: "#faa968", background: "#05182e" },
	{ id: "ristretto", label: "Ristretto", mode: "dark", accent: "#f38d70", background: "#2c2525" },
	{ id: "rose-pine", label: "Rose Pine", mode: "light", accent: "#56949f", background: "#faf4ed" },
	{ id: "solitude", label: "Solitude", mode: "dark", accent: "#798186", background: "#101315" },
	{ id: "tokyo-night", label: "Tokyo Night", mode: "dark", accent: "#7aa2f7", background: "#1a1b26" },
	{ id: "vantablack", label: "Vantablack", mode: "dark", accent: "#8d8d8d", background: "#000000" },
	{ id: "white", label: "White", mode: "light", accent: "#6e6e6e", background: "#ffffff" },
];
