/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors/$authorId'
import { Route as PluginsPluginIdRouteImport } from './routes/plugins/$pluginId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/badges.lazy').then((d) => d.Route))
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/categories.lazy').then((d) => d.Route))
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/health.lazy').then((d) => d.Route))
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/leaderboards.lazy').then((d) => d.Route))
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/authors/$authorId.lazy').then((d) => d.Route),
)
const PluginsPluginIdRoute = PluginsPluginIdRouteImport.update({
  id: '/plugins/$pluginId',
  path: '/plugins/$pluginId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/plugins/$pluginId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/categories': typeof CategoriesRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/categories': typeof CategoriesRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/categories': typeof CategoriesRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/categories'
    | '/health'
    | '/leaderboards'
    | '/authors/$authorId'
    | '/plugins/$pluginId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badges'
    | '/categories'
    | '/health'
    | '/leaderboards'
    | '/authors/$authorId'
    | '/plugins/$pluginId'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/categories'
    | '/health'
    | '/leaderboards'
    | '/authors/$authorId'
    | '/plugins/$pluginId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  CategoriesRoute: typeof CategoriesRoute
  HealthRoute: typeof HealthRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  PluginsPluginIdRoute: typeof PluginsPluginIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId': {
      id: '/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  CategoriesRoute: CategoriesRoute,
  HealthRoute: HealthRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  PluginsPluginIdRoute: PluginsPluginIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
